#!/bin/bash
#
# Copyright (c) 2024 by Thomas A. Early N7TAE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

trap ControlC INT

ControlC () {
	echo "caught SIGINT"
}

# Execution starts here!

# service file locations
urfserv='/etc/systemd/system/urfd.service'
tcdserv='/etc/systemd/system/tcd.service'

if [[ -e urfd.ini ]]; then
	callsign=$(awk '$1 == "Callsign"{print $3}' urfd.ini)
else
	echo "ERROR: urfd.ini! You'll have to specify it."
	exit 1
fi


key='x'
# main loop
while [[ "$key" != q* ]]
do
	clear
	pcount=$(ps -aux | grep -e urfd -e tcd | wc -l)
	if [ "$pcount" -gt 1 ]; then
		echo
		ps -aux | head -1
		ps -aux | grep -e urfd -e tcd | grep -vE 'grep|journalctl'
	fi
	echo
	echo "        Reflector Administration, Version #240823"
	echo
	echo "                         $callsign"
	echo
	git status | head -1
	echo
	if [ -e $urfserv -o -e $tcdserv ]; then
		echo "us : Uninstall $callsign"
		if [ -e $urfserv ]; then
			echo "rl : Reflector log"
		fi
		if [ -e $tcdserv ]; then
			echo "tl : Transcoder log"
		fi
		if [ -e $urfserv ]; then
			echo "rr : Reflector restart"
		fi
		if [ -e $tcdserv ]; then
			echo "tr : Transcoder restart"
		fi
	else
		if [ -e reflector/urfd -a -e ../tcd/tcd ]; then
			echo "is : Install $callsign"
		fi
	fi
	echo
	echo    "q  : Quit"
	echo
	read -p "Please input command : " key garbage

	if   [[ "$key" == us* ]]; then
		if [ -e $urfserv -o -e $tcdserv ]; then
			sudo make uninstall
		fi
	elif [[ "$key" == is* ]]; then
		if [ -e reflector/urfd -a -e transcoder/tcd -a ! -e $urfserv -a ! -e $tcdserv ]; then
			sudo make install
		fi
	elif [[ "$key" == rr* ]]; then
		if [ -e $urfserv ]; then
			sudo systemctl restart urfd
		fi
	elif [[ "$key" == tr* ]]; then
		if [ -e $tcdserv ]; then
			sudo systemctl restart tcd
		fi
	elif [[ "$key" == tl* ]]; then
		if [ -e $tcdserv ]; then
			sudo journalctl -u tcd -f
		fi
	elif [[ "$key" == rl* ]]; then
		if [ -e $urfserv ]; then
			sudo journalctl -u urfd -f
		fi
	fi
done
exit 0
